apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gitops
  namespace: estudos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-gitops
  template:
    metadata:
      labels:
        app: nginx-gitops
    spec:
      containers:
      - name: nginx
        image: ghcr.io/robertcs1507/argocd-lab:13f172df088b0482a087e9fe89ca173e1adf38ad
        ports:
        - containerPort: 80
