apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gitops
  namespace: estudos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-gitops
  template:
    metadata:
      labels:
        app: nginx-gitops
    spec:
      containers:
      - name: nginx
        image: ghcr.io/robertcs1507/argocd-lab:latest
        ports:
        - containerPort: 80
