name: Build e Deploy GitOps

on:
  push:
    branches:
      - main
    paths:
      - "app/**"

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build e Push
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: true
          tags: |
            ghcr.io/robertcs1507/argocd-lab:${{ github.sha }}
            ghcr.io/robertcs1507/argocd-lab:latest

      - name: Atualizar manifesto GitOps
        run: |
          sed -i "s|image: ghcr.io/robertcs1507/argocd-lab:.*|image: ghcr.io/robertcs1507/argocd-lab:${GITHUB_SHA}|" deployment.yaml

      - name: Commit da nova imagem
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add deployment.yaml

          if git diff --cached --quiet; then
            echo "Nenhuma alteração no manifesto"
          else
            git commit -m "Atualiza imagem para ${GITHUB_SHA} [skip ci]"
            git push
          fi
